BASE: 'configs/GLDv2/GLDv2_base.yml'

MODEL:
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: '/home/gongyou.zyq/ILR2021/logs/GLDv2clean/R50/R50_256_finetune/resnet50_6.pth'
  NAME: 'resnet50'

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PADDING: 10
  RE_PROB: 1.0 # random erasing

DATALOADER:
  CACHE_LIST: 'cache_all_list.pkl'
  SAMPLER: 'gld'

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 2
  BASE_LR: 0.008
  IMS_PER_BATCH: 128    # 16G: 128
  CHECKPOINT_PERIOD: 2
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WARMUP_EPOCHS: 0.0
  COSINE_MARGIN: 0.3
  COSINE_SCALE: 30

TEST:
  IMS_PER_BATCH: 128

OUTPUT_DIR: 'logs/GLDv2clean/R50_256_finetune'
