BASE: 'configs/GLDv2/GLDv2_base.yml'

MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/gongyou.zyq/.torch/models/resnet50-19c8e357.pth'
  NAME: 'resnet50'

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PADDING: 10

DATALOADER:
  CACHE_LIST: 'cache_clean_list.pkl'

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 10
  BASE_LR: 0.08
  IMS_PER_BATCH: 128    # 16G: 128
  CHECKPOINT_PERIOD: 2
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WARMUP_EPOCHS: 1.0
  COSINE_MARGIN: 0.3
  COSINE_SCALE: 30

TEST:
  IMS_PER_BATCH: 128

OUTPUT_DIR: 'logs/GLDv2clean/R50_256'
