BASE: 'configs/GLDv2/GLDv2_base.yml'

MODEL:
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: '/home/gongyou.zyq/ILR2021/logs/GLDv2clean/ResNeSt/ResNest269_448/resnest269_10.pth'
  NAME: 'resnest269'

INPUT:
  SIZE_TRAIN: [448, 448]
  SIZE_TEST: [448, 448]
  PADDING: 18

DATALOADER:
  CACHE_LIST: 'cache_c2f_list.pkl'

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 6
  BASE_LR: 0.008
  IMS_PER_BATCH: 28    # 16G: 12, 32G: 28
  CHECKPOINT_PERIOD: 2
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WARMUP_EPOCHS: 0.0
  COSINE_MARGIN: 0.3
  COSINE_SCALE: 30

TEST:
  IMS_PER_BATCH: 28

OUTPUT_DIR: 'logs/GLDv2clean/ResNeSt269_448_finetune'
