BASE: 'configs/GLDv2/GLDv2_base.yml'

MODEL:
  NUM_CLASSES: 203094
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: '/home/gongyou.zyq/ILR2021/logs/GLDv2clean/ResNeSt/ResNeSt269_448_finetune/resnest269_4.pth'
  NAME: 'resnest269'

INPUT:
  SIZE_TRAIN: [512, 512]
  SIZE_TEST: [512, 512]
  PADDING: 20

DATALOADER:
  CACHE_LIST: 'cache_full_list.pkl'

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 2
  BASE_LR: 0.0008
  IMS_PER_BATCH: 6    # 16G: 12, 32G: 20
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WARMUP_EPOCHS: 0.0
  COSINE_MARGIN: 0.0
  COSINE_SCALE: 60

TEST:
  IMS_PER_BATCH: 16

OUTPUT_DIR: 'logs/GLDv2clean/ResNeSt269_512_finetune'
