BASE: 'configs/GLDv2/GLDv2_base.yml'

MODEL:
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: '/home/gongyou.zyq/ILR2021/logs/GLDv2clean/IBN-Net/RXt101ibn_512_finetune/resnext101_ibn_a_2.pth'
  NAME: 'resnext101_ibn_a'

INPUT:
  SIZE_TRAIN: [512, 512]
  SIZE_TEST: [512, 512]
  PADDING: 20

DATALOADER:
  CACHE_LIST: 'cache_all_list.pkl'
  SAMPLER: 'gld'

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 4
  BASE_LR: 0.0008
  IMS_PER_BATCH: 18    # 16G: 20, 32G: 48
  CHECKPOINT_PERIOD: 2
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  1e-5
  WEIGHT_DECAY_BIAS: 1e-5
  WARMUP_EPOCHS: 0.0
  COSINE_MARGIN: 0.3
  COSINE_SCALE: 30

TEST:
  IMS_PER_BATCH: 18

OUTPUT_DIR: 'logs/GLDv2clean/RXt101ibn_512_all'
