BASE: 'configs/GLDv2/GLDv2_base.yml'

MODEL:
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: '/home/gongyou.zyq/ILR2021/logs/GLDv2clean/IBN-Net/SER101ibn_384/se_resnet101_ibn_a_10.pth'
  NAME: 'se_resnet101_ibn_a'

INPUT:
  SIZE_TRAIN: [384, 384]
  SIZE_TEST: [384, 384]
  PADDING: 15

DATALOADER:
  CACHE_LIST: 'cache_c2f_list.pkl'

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 6
  BASE_LR: 0.008
  IMS_PER_BATCH: 96    # 16G: 40, 32G: 96
  CHECKPOINT_PERIOD: 2
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WARMUP_EPOCHS: 0.0
  COSINE_MARGIN: 0.3
  COSINE_SCALE: 30

TEST:
  IMS_PER_BATCH: 96

OUTPUT_DIR: 'logs/GLDv2clean/SER101ibn_384_finetune'
